### ISSUE TITLE
Test data for crypto library

### ISSUE THREAD

**Issue by jannikluhn** [shutter-network/shutter#105]
We need to generate test data for our crypto library to make it easier for others to create third party implementations. The data should be in one or more JSON files (similar to existing Ethereum tests).

The functions we need to provide test inputs for are:

- [`func Encrypt(message []byte, eonPublicKey *EonPublicKey, epochID *EpochID, sigma Block) *EncryptedMessage`](https://github.com/shutter-network/shutter/blob/main/shlib/shcrypto/encryption.go#L50)
- [`func (m *EncryptedMessage) Decrypt(epochSecretKey *EpochSecretKey) ([]byte, error)`](https://github.com/shutter-network/shutter/blob/main/shlib/shcrypto/encryption.go#L99)
- [`func VerifyEpochSecretKey(epochSecretKey *EpochSecretKey, eonPublicKey *EonPublicKey, epochIDBytes []byte) (bool, error)`](https://github.com/shutter-network/shutter/blob/main/shlib/shcrypto/keys.go#L212)

Inputs and outputs should be hex encoded. In particular `EpochIDs` should be byte strings that first have to be run through [`ComputeEpochID`](https://github.com/shutter-network/shutter/blob/main/shlib/shcrypto/keys.go#L145).

Instead of generating the data manually, it is probably easier to write a simple generator executable. It could be a standalone program or a subcommand under `rolling-shutter`.

**Comment by konradkonrad** [comment]
Closed through https://github.com/shutter-network/rolling-shutter/pull/416
